### ISSUE TITLE
markup text is move to right

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports#9]
![test report](https://user-images.githubusercontent.com/6592592/48736112-a385f380-ec4a-11e8-92aa-b650789e9a10.png)

`ExtentTestManager.getEndNode().log(Status.INFO, MarkupHelper.createLabel(login, ExtentColor.BLUE));`

version 4.0.4

**Comment by foursyth** [comment]
Hello @mmajcherczyk 

We are aware of this, and its due to the changes in the underlying toolkit.  We will make this part of the next release but for now, you can use the following styles to fix:

```
span.badge { float: none; margin-left: auto; }
```

PS. this will be included inside `<style>`, or `<css>` in your configuration xml or `reporter.config().setCSS()` from Java.

**Comment by mmajcherczyk** [comment]
change in config().setCSS() working 
thx
